// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALv4ZHpcLqlwQH7dq3y4eH1bTRjnDJBcw',
    appId: '1:497155274124:web:c86cdc7a3ff40338bf12a9',
    messagingSenderId: '497155274124',
    projectId: 'quiz-app-77d9b',
    authDomain: 'quiz-app-77d9b.firebaseapp.com',
    storageBucket: 'quiz-app-77d9b.appspot.com',
    measurementId: 'G-FKYHWMNTKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwdqwTx9-2RATPixZBHXDgpLcIrScaYl4',
    appId: '1:497155274124:android:e3884cdbe371cba6bf12a9',
    messagingSenderId: '497155274124',
    projectId: 'quiz-app-77d9b',
    storageBucket: 'quiz-app-77d9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-Gq4FNLcW2ICBVuHGcHxNu5G0foQcaQ',
    appId: '1:497155274124:ios:bf59651bd18e559ebf12a9',
    messagingSenderId: '497155274124',
    projectId: 'quiz-app-77d9b',
    storageBucket: 'quiz-app-77d9b.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-Gq4FNLcW2ICBVuHGcHxNu5G0foQcaQ',
    appId: '1:497155274124:ios:bf59651bd18e559ebf12a9',
    messagingSenderId: '497155274124',
    projectId: 'quiz-app-77d9b',
    storageBucket: 'quiz-app-77d9b.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALv4ZHpcLqlwQH7dq3y4eH1bTRjnDJBcw',
    appId: '1:497155274124:web:b6d617374e98f2cbbf12a9',
    messagingSenderId: '497155274124',
    projectId: 'quiz-app-77d9b',
    authDomain: 'quiz-app-77d9b.firebaseapp.com',
    storageBucket: 'quiz-app-77d9b.appspot.com',
    measurementId: 'G-GMJH4XFM0F',
  );
}
